% \\contentsline {chapter}{\\numberline {(\d)}([\s\w]*)}\{\d*\}{chapter.\d*}
% cd ..; mkdir  Chapter\1_\2;cd  Chapter\1; 

%\\contentsline {section}{\\numberline {([\d\.]*)}([\s\w]*)}\{\d*\}{chapter[\d\.]*}

%\\contentsline {subsubsection}{([\s\w]*)}{\d*}{section\*[\d\.]*}
% cd ..; mkdir  Subsubsection_\1;cd  Subsubsection_\1; 

 mkdir  Chapter_1_Motivation;
        cd     Chapter_1_Motivation; 
        touch  Chapter_1_Motivation.nb; 
 mkdir  Section_1-1_Choosing_a_Color_Space;
        cd     Section_1-1_Choosing_a_Color_Space; 
        touch  Section_1-1_Choosing_a_Color_Space.nb; 
 cd ..; mkdir  Section_1-2_Physiology_Study;
        cd     Section_1-2_Physiology_Study; 
        touch  Section_1-2_Physiology_Study.nb; 
        mkdir  Subsection_1-2-1_Chromophores_in_Human_Skin;
        cd     Subsection_1-2-1_Chromophores_in_Human_Skin; 
        touch  Subsection_1-2-1_Chromophores_in_Human_Skin.nb; 
 cd ..; mkdir  Subsection_1-2-2_Response_Spectra;
        cd     Subsection_1-2-2_Response_Spectra; 
        touch  Subsection_1-2-2_Response_Spectra.nb; 
 cd ..; mkdir  Subsection_1-2-3_Skin_Color_Simulation;
        cd     Subsection_1-2-3_Skin_Color_Simulation; 
        touch  Subsection_1-2-3_Skin_Color_Simulation.nb; 
 cd ../..;
 cd ..; mkdir  Chapter_2_Color_Spaces_and_Information_Storage_for_Computer_Vision_Processing;
        cd     Chapter_2_Color_Spaces_and_Information_Storage_for_Computer_Vision_Processing; 
        touch  Chapter_2_Color_Spaces_and_Information_Storage_for_Computer_Vision_Processing.nb; 
        mkdir  Section_2-1_Constructing_a_New_Color_Space;
        cd     Section_2-1_Constructing_a_New_Color_Space; 
        touch  Section_2-1_Constructing_a_New_Color_Space.nb; 
        mkdir  Subsection_2-1-1_Camera_RGB_and_Normalization_for_Discrete_Range;
        cd     Subsection_2-1-1_Camera_RGB_and_Normalization_for_Discrete_Range; 
        touch  Subsection_2-1-1_Camera_RGB_and_Normalization_for_Discrete_Range.nb; 
 cd ..; mkdir  Subsection_2-1-2_Rotation_Matrix;
        cd     Subsection_2-1-2_Rotation_Matrix; 
        touch  Subsection_2-1-2_Rotation_Matrix.nb; 
 cd ..; mkdir  Subsection_2-1-3_Representing_the_Rotation;
        cd     Subsection_2-1-3_Representing_the_Rotation; 
        touch  Subsection_2-1-3_Representing_the_Rotation.nb; 
        mkdir  Subsubsection_Principles_of_Optimization;
        cd     Subsubsection_Principles_of_Optimization; 
        touch  Subsubsection_Principles_of_Optimization.nb; 
 cd ..; mkdir  Subsubsection_Factoring_the_Rotation;
        cd     Subsubsection_Factoring_the_Rotation; 
        touch  Subsubsection_Factoring_the_Rotation.nb; 
 cd ..; mkdir  Subsubsection_Quantizing_the_Rotation;
        cd     Subsubsection_Quantizing_the_Rotation; 
        touch  Subsubsection_Quantizing_the_Rotation.nb; 
 cd ../..
 cd ..; mkdir  Section_2-2_Preservation_of_Color_Information;
        cd     Section_2-2_Preservation_of_Color_Information; 
        touch  Section_2-2_Preservation_of_Color_Information.nb; 
        mkdir  Subsection_2-2-1_Partition;
        cd     Subsection_2-2-1_Partition; 
        touch  Subsection_2-2-1_Partition.nb; 
 cd ..; mkdir  Subsection_2-2-2_Linear;
        cd     Subsection_2-2-2_Linear; 
        touch  Subsection_2-2-2_Linear.nb; 
 cd ..; mkdir  Subsection_2-2-3_ERF;
        cd     Subsection_2-2-3_ERF; 
        touch  Subsection_2-2-3_ERF.nb;
 cd ..; mkdir  Subsection_2-2-4_Efficiently_Implementing_the_Distribution_Function;
        cd     Subsection_2-2-4_Efficiently_Implementing_the_Distribution_Function; 
        touch  Subsection_2-2-4_Efficiently_Implementing_the_Distribution_Function.nb; 
        mkdir  Subsubsection_The_Region_Which_Discards_All_Information;
        cd     Subsubsection_The_Region_Which_Discards_All_Information; 
        touch  Subsubsection_The_Region_Which_Discards_All_Information.nb; 
 cd ..; mkdir  Subsubsection_The_Region_Which_Keeps_All_Information;
        cd     Subsubsection_The_Region_Which_Keeps_All_Information; 
        touch  Subsubsection_The_Region_Which_Keeps_All_Information.nb; 
 cd ..; mkdir  Subsubsection_The_compression_ratio;
        cd     Subsubsection_The_compression_ratio; 
        touch  Subsubsection_The_compression_ratio.nb; 
 cd ..; mkdir  Subsubsection_A_Piecewise_Approximation_to_the_ERF_Distribution;
        cd     Subsubsection_A_Piecewise_Approximation_to_the_ERF_Distribution; 
        touch  Subsubsection_A_Piecewise_Approximation_to_the_ERF_Distribution.nb; 
 cd ../..
 cd ..; mkdir  Section_2-3_The_Skin_Color_Space_Algorithm;
        cd     Section_2-3_The_Skin_Color_Space_Algorithm; 
        touch  Section_2-3_The_Skin_Color_Space_Algorithm.nb; 
        mkdir  Subsubsection_Setting_the_Value_for_the_Tolerance;
        cd     Subsubsection_Setting_the_Value_for_the_Tolerance; 
        touch  Subsubsection_Setting_the_Value_for_the_Tolerance.nb; 
 cd ..; mkdir  Subsubsection_The_complete_algorithm;
        cd     Subsubsection_The_complete_algorithm; 
        touch  Subsubsection_The_complete_algorithm.nb; 
 cd ..; mkdir  Subsubsection_Conclusion;
        cd     Subsubsection_Conclusion; 
        touch  Subsubsection_Conclusion.nb; 
 cd ../..
 cd ..; mkdir  Chapter_3_Skin_Statistics;
        cd     Chapter_3_Skin_Statistics; 
        touch  Chapter_3_Skin_Statistics.nb; 
        mkdir  Section_3-1_Chromatic_Target_Model;
        cd     Section_3-1_Chromatic_Target_Model; 
        touch  Section_3-1_Chromatic_Target_Model.nb; 
 cd ..; mkdir  Section_3-2_Algorithm_for_Generating_the_Model;
        cd     Section_3-2_Algorithm_for_Generating_the_Model; 
        touch  Section_3-2_Algorithm_for_Generating_the_Model.nb; 
        mkdir  Subsection_3-2-1_RGB_Bin_allocation;
        cd     Subsection_3-2-1_RGB_Bin_allocation; 
        touch  Subsection_3-2-1_RGB_Bin_allocation.nb; 
 cd ..; mkdir  Subsection_3-2-2_Skinning_the_Bins;
        cd     Subsection_3-2-2_Skinning_the_Bins; 
        touch  Subsection_3-2-2_Skinning_the_Bins.nb; 
 cd ..; mkdir  Subsection_3-2-3_Rotating_the_Bins;
        cd     Subsection_3-2-3_Rotating_the_Bins; 
        touch  Subsection_3-2-3_Rotating_the_Bins.nb; 
 cd ..; mkdir  Subsection_3-2-4_Top_and_Tail;
        cd     Subsection_3-2-4_Top_and_Tail; 
        touch  Subsection_3-2-4_Top_and_Tail.nb; 
 cd ..; mkdir  Subsection_3-2-5_Collapse_the_Bins;
        cd     Subsection_3-2-5_Collapse_the_Bins; 
        touch  Subsection_3-2-5_Collapse_the_Bins.nb; 
 cd ..; mkdir  Subsection_3-2-6_De-Speckle_the_Bin_Values; 
        cd     Subsection_3-2-6_De-Speckle_the_Bin_Values; 
        touch  Subsection_3-2-6_De-Speckle_the_Bin_Values.nb; 
 cd ..; mkdir  Subsection_3-2-7_Blob_Detection;
        cd     Subsection_3-2-7_Blob_Detection; 
        touch  Subsection_3-2-7_Blob_Detection.nb; 
 cd ..; mkdir  Subsection_3-2-8_The_Gaussian_Fit;
        cd     Subsection_3-2-8_The_Gaussian_Fit; 
        touch  Subsection_3-2-8_The_Gaussian_Fit.nb; 
 cd ..;
 cd ..; mkdir  Section_3-3_iPhone_Camera_Characteristics;
        cd     Section_3-3_iPhone_Camera_Characteristics; 
        touch  Section_3-3_iPhone_Camera_Characteristics.nb; 
 cd ..; mkdir  Section_3-4_Implementation_of_Skin_Color_Space_Statistics_in_Matlab;
        cd     Section_3-4_Implementation_of_Skin_Color_Space_Statistics_in_Matlab; 
        touch  Section_3-4_Implementation_of_Skin_Color_Space_Statistics_in_Matlab.nb; 
        mkdir  Subsection_3-4-1_Transformation_with_Zero_Angle;
        cd     Subsection_3-4-1_Transformation_with_Zero_Angle; 
        touch  Subsection_3-4-1_Transformation_with_Zero_Angle.nb; 
 cd ..; mkdir  Subsection_3-4-2_Removing_Zeroes;
        cd     Subsection_3-4-2_Removing_Zeroes; 
        touch  Subsection_3-4-2_Removing_Zeroes.nb; 
 cd ..; mkdir  Subsection_3-4-3_White-Out_and_Black-Out; 
           cd     Subsection_3-4-3_White-Out_and_Black-Out; 
        touch  Subsection_3-4-3_White-Out_and_Black-Out.nb; 
 cd ..; mkdir  Subsection_3-4-4_Removing_the_Background_Distribution;
        cd     Subsection_3-4-4_Removing_the_Background_Distribution; 
        touch  Subsection_3-4-4_Removing_the_Background_Distribution.nb; 
 cd ..; mkdir  Subsection_3-4-5_Results;
        cd     Subsection_3-4-5_Results; 
        touch  Subsection_3-4-5_Results.nb; 
 cd ../..
 cd ..; mkdir  Chapter_4_Pattern_Recognition;
        cd     Chapter_4_Pattern_Recognition; 
        touch  Chapter_4_Pattern_Recognition.nb; 
        mkdir  Subsection_4-1_Improved_Contour_Detection; 
        cd     Subsection_4-1_Improved_Contour_Detection; 
        touch  Subsection_4-1_Improved_Contour_Detection.nb
 cd ..; mkdir  Subsection_4-2_Fingertip_Descriptor; 
        cd     Subsection_4-2_Fingertip_Descriptor; 
        touch  Subsection_4-2_Fingertip_Descriptor.nb
 cd ..; mkdir  Subsection_4-3_Putting_it_All_Together; 
        cd     Subsection_4-3_Putting_it_All_Together; 
        touch  Subsection_4-3_Putting_it_All_Together.nb
 cd ..; mkdir  Subsection_4-3-1_Detecting_a_Finger_Press; 
        cd     Subsection_4-3-1_Detecting_a_Finger_Press; 
        touch  Subsection_4-3-1_Detecting_a_Finger_Press.nb;
 cd ..; mkdir  Subsection_4-4_Skin_Detection; 
        cd     Subsection_4-4_Skin_Detection; 
        touch  Subsection_4-4_Skin_Detection.nb;
 cd ..;
 cd ..; mkdir  Chapter_5_Future_Work_and_Discussion;
        cd     Chapter_5_Future_Work_and_Discussion; 
        touch  Chapter_5_Future_Work_and_Discussion.nb; 
